#[derive(Debug, Clone, PartialEq)]
pub enum Symbols {
    Circle,
    Hashtag,
    Dollar,
    AtSign,
    Seven,
    Astrisk,
    AndSign,
    Jackpot,
    Wild,
}

impl Symbols {
    pub fn get_value(&self) -> i32 {
        match self {
            Symbols::Circle => 1,
            Symbols::Hashtag => 1,
            Symbols::Dollar => 1,
            Symbols::AtSign => 1,
            Symbols::Seven => 2,
            Symbols::Astrisk => 2,
            Symbols::AndSign => 2,
            Symbols::Jackpot => 7,
            Symbols::Wild => 0,
        }
    }
}

pub const REEL_STRIPS: [[Symbols; 20]; 5] = [
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
        Symbols::Wild,
        Symbols::Wild,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
        Symbols::Wild,
        Symbols::Wild,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
        Symbols::Wild,
        Symbols::Wild,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
        Symbols::Wild,
        Symbols::Wild,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
        Symbols::Wild,
        Symbols::Wild,
    ],
];
