#[derive(Debug, Clone)]
pub enum Symbols {
    Circle,
    Hashtag,
    Dollar,
    AtSign,
    Seven,
    Astrisk,
    AndSign,
    Jackpot,
}

impl Symbols {
    pub fn get_value(&self) -> i32 {
        match self {
            Symbols::Circle => 2,
            Symbols::Hashtag => 3,
            Symbols::Dollar => 5,
            Symbols::AtSign => 5,
            Symbols::Seven => 7,
            Symbols::Astrisk => 10,
            Symbols::AndSign => 10,
            Symbols::Jackpot => 50,
        }
    }
}

pub const REEL_STRIPS: [[Symbols; 24]; 5] = [
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Astrisk,
        Symbols::Jackpot,
    ],
    [
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Circle,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Hashtag,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::Dollar,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::AtSign,
        Symbols::Seven,
        Symbols::Seven,
        Symbols::AndSign,
        Symbols::Astrisk,
        Symbols::Jackpot,
    ],
];
